apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: inlove433258/my-app:latest  # Public Docker Hub image
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app  # Must match the labels in the deployment
  ports:
    - protocol: TCP
      port: 80      # Port the service exposes
      targetPort: 80 # Port the container listens on
  type: LoadBalancer  # Exposes the service externally (for cloud environments)
